kasugaijin/baja-pet-rescue

app/controllers/adopter_applications_controller.rb, app/controllers/organization_dogs_controller.rb, app/helpers/adopter_applications_helper.rb, app/models/adopter_account.rb, app/models/adopter_application.rb, app/models/application.rb, app/models/user.rb, app/views/adoptable_dogs/show.html.erb, app/views/adopter_profiles/_applications.html.erb, app/views/adopter_profiles/show.html.erb, config/routes.rb, db/migrate/20220801222016_change_status_column_in_application.rb, db/migrate/20220801224047_rename_applications.rb, db/migrate/20220801231117_change_status_in_adopter_applications.rb, db/schema.rb, test/controllers/adopter_applications_controller_test.rb
Adopter applications feature working.
=> Adopter applications

app/controllers/adoption_application_reviews_controller.rb, app/controllers/adoptions_controller.rb, app/controllers/profile_reviews_controller.rb, app/helpers/adoption_application_reviews_helper.rb, app/models/adopter_account.rb, app/models/adopter_application.rb, app/models/adopter_profile.rb, app/models/adoption.rb, app/models/dog.rb, app/models/staff_account.rb, app/views/adopter_profiles/_applications.html.erb, app/views/adoption_application_reviews/_search_results.html.erb, app/views/adoption_application_reviews/edit.html.erb, app/views/adoption_application_reviews/index.html.erb, app/views/devise/shared/_links.html.erb, app/views/static_pages/home.html.erb, config/routes.rb, db/migrate/20220804181025_create_adoptions.rb, db/migrate/20220805040425_add_notes_to_adopter_applications.rb, db/migrate/20220805221902_remove_adopter_application_id_from_adoptions.rb, db/migrate/20220805222108_add_adopter_account_to_adoptions.rb, db/schema.rb, test/controllers/adoption_application_reviews_controller_test.rb
Staff app review basic functionality working: can review all dogs that have apps and no adoption, review applicant profile, edit application to update status and make notes, create adoption.
=> Staff app reviews

app/controllers/adopter_applications_controller.rb, app/controllers/organization_dogs_controller.rb, app/models/adoption.rb, app/views/adoptable_dogs/index.html.erb, app/views/adoptable_dogs/show.html.erb, app/views/organization_dogs/index.html.erb, app/views/static_pages/home.html.erb
Add to org dogs index page the ability to filters all dogs based on adoption status and/or name via the controller and views.
=> Org dogs buildout

Gemfile.lock, app/controllers/adopter_profiles_controller.rb, app/helpers/adopter_profile_helper.rb, app/models/adopter_profile.rb, app/views/adopter_profiles/_form.html.erb, app/views/adopter_profiles/new.html.erb, app/views/adopter_profiles/show.html.erb, db/migrate/20220812185732_remove_columns_from_adopter_profiles.rb, db/migrate/20220812190121_add_columns_to_adopter_profiles.rb, db/schema.rb
Adopter profile markup complete with all questions and input fields in form. 
Validations on model in place. Note that fields that appear conditionally e.g., after a boolean question, do not have a model validation as they need to be hidden in one case and submitted blank. 
Form is tested and works as intended so far. 
No JavaScript added yet for client side validations or conditionally displaying form fields.
=> Adopter profile form

Gemfile, Gemfile.lock, app/controllers/adopter_profiles_controller.rb, app/javascript/controllers/counter_controller.js, app/javascript/controllers/display_controller.js, app/models/adopter_profile.rb, app/views/adopter_profiles/_form.html.erb, config/initializers/phonelib.rb
Add adopter profile functionality:
- form partial with all markup for form fields and errors
- stimulus js for character counter, limit and conditionally showing certain input fields
- adopter profile model validations and methods for phone number validation, normalization, humanization
=> Adopter profile javascript

app/views/adopter_profiles/_form.html.erb, app/views/adopter_profiles/show.html.erb
add markup for adopter profile show page
=> Adopter profile show

app/assets/stylesheets/application.scss, app/controllers/organization_dogs_controller.rb, app/models/dog.rb, app/views/adopter_profiles/show.html.erb, app/views/organization_dogs/_form.html.erb, app/views/organization_dogs/edit.html.erb, db/migrate/20220819220558_add_columns_to_dogs.rb, db/migrate/20220819225621_add_sexto_dogs.rb, db/migrate/20220819231818_remove_name_from_dogs.rb, db/migrate/20220819231929_add_name_to_dogs.rb, db/schema.rb, db/seeds.rb
Add additional columns/attributes to Dogs table
Add these inputs to org dog form partial
validate inputs on Dog model
Ste name of dog to unique both in database and model validation
=> Org dog form

app/assets/stylesheets/application.scss, app/views/static_pages/about_us.html.erb, app/views/static_pages/donate.html.erb, app/views/static_pages/faq.html.erb, app/views/static_pages/partners.html.erb, app/views/static_pages/privacy_policy.html.erb, app/views/static_pages/terms_and_conditions.html.erb
=> Ami's commits on August 29th

app/assets/stylesheets/application.scss, app/views/static_pages/about_us.html.erb, app/views/static_pages/home.html.erb, app/views/static_pages/partners.html.erb
=> Ami's August 29 commits #2

app/assets/stylesheets/application.scss, app/controllers/registrations_controller.rb, app/views/adoptable_dogs/index.html.erb, app/views/adoptable_dogs/show.html.erb, app/views/adopter_profiles/_applications.html.erb, app/views/adopter_profiles/_form.html.erb, app/views/adopter_profiles/edit.html.erb, app/views/adopter_profiles/new.html.erb, app/views/adopter_profiles/show.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/organization_dogs/index.html.erb, app/views/static_pages/about_us.html.erb, app/views/static_pages/account_select.html.erb, app/views/static_pages/donate.html.erb, app/views/static_pages/faq.html.erb, app/views/static_pages/home.html.erb, app/views/static_pages/partners.html.erb, app/views/static_pages/privacy_policy.html.erb, app/views/static_pages/terms_and_conditions.html.erb
Please review and merge. Thank you!
=> Ami August 30 commits

app/views/adopter_profiles/_form.html.erb, app/views/adopter_profiles/show.html.erb, app/views/adoption_application_reviews/index.html.erb, app/views/devise/registrations/edit.html.erb, app/views/organization_dogs/index.html.erb
Please review and merge. Thank you!
=> Ami August 30th commits #2

app/views/adopter_profiles/_applications.html.erb, app/views/adopter_profiles/_form.html.erb, app/views/adopter_profiles/edit.html.erb, app/views/adopter_profiles/show.html.erb, app/views/adoption_application_reviews/_search_results.html.erb, app/views/adoption_application_reviews/edit.html.erb, app/views/adoption_application_reviews/index.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/organization_dogs/index.html.erb, app/views/static_pages/account_select.html.erb
=> Ami's August 31 commits

app/views/contacts/new.html.erb, test/integration/contact_form_test.rb
**Summary of changes:**
* Added validation messages to the contact form, they were missing (`views/contacts/new.html.erb`)
* Added a couple of integration tests to test the presence of validation messages, then a test for successful submission
**Closes issue:** #44
=> Contact form tests

app/controllers/adopter_applications_controller.rb, test/fixtures/adopter_applications.yml, test/fixtures/adoptions.yml, test/fixtures/dogs.yml, test/integration/adoptable_dog_show_test.rb, test/integration/adopter_applications_page_test.rb
Test suite for adopter user applications page
=> Adopter applications test

app/views/adopter_profiles/_form.html.erb, test/fixtures/adopter_profiles.yml, test/integration/adopter_profile_form_test.rb, test/system/adopter_profile_forms_test.rb
PR to add system tests for the adopter profile to check javascript works as expected
Also a test added to integration test for the adopter profile to check radios are correctly loaded with selected values on form edit
=> Adopter profile sys test

test/integration/adoption_application_reviews_test.rb
Closes Issue #49 
Let me know what you think! Also, would you like to test that unverified staff cannot create an adoption?
=> More adoption review tests

app/controllers/adoptions_controller.rb, app/models/adopter_application.rb, app/views/organization_dogs/show.html.erb, config/routes.rb
Add ability to revoke an adoption, which sets the dog to not adopted, and the successful application status to `withdrawn`
=> Revoke adoption

README.md
**This PR:**
- Changes ruby version instruction to look for the correct version in the user's list of installed Ruby versions rather than looking at their global install.
- Combines the database setup commands into the `rails db:setup`
Closes: #116
=> Streamline dev environment setup instructions in README

app/views/layouts/application.html.erb
=> Use Time object to return the current year dynamically

test/fixtures/locations.yml, test/integration/static_pages_test.rb, test/integration/successes_page_test.rb
test the successes page renders appropriate html elements for the google map api call
=> Success feature

app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb
=> add successes url to the navbar

app/views/layouts/application.html.erb
This PR moves the Donate link to the main navigation bar for better visibility, and Successes link was moved to the Info drop down menu on the navigation bar. Screenshot shows the new navigation bar with Info dropdown menu.
=> Updated the navigation bar position of the donate and success links.

README.md
Update readme for contribution guidelines
=> update contribution guidelines
